[theme]
primaryColor = "#E91E63"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#2C3E50"

[server]
maxUploadSize = 50
maxMessageSize = 50

[browser]
gatherUsageStats = false
